<?php
/*
  $Id$
  part of TeeBX(R) VoIP communication platform. http://www.teebx.com
*/

	$prompt_languages = array(
		'en-us' => gettext('English (US)'),
		'en-gb' => gettext('English (UK)'),
		'da-dk' => gettext('Danish'),
		'nl-nl' => gettext('Dutch'),
		// 'fr' => gettext('French (France)'),
		'fr-ca' => gettext('French (Canada)'),
		'de-de' => gettext('German'),
		'it-it' => gettext('Italian'),
		'ja-jp' => gettext('Japanese'),
		'pl-pl' => gettext('Polish'),
		'pt-br' => gettext('Portuguese (Brazil)'),
		'ru-ru' => gettext('Russian'),
		'es-es' => gettext('Spanish (Spain)')
		// 'se' => gettext('Swedish')
	);
?>