<?php
/*
  $Id$
  part of TeeBX(R) VoIP communication platform. http://www.teebx.com
*/

	$prompt_languages = array(
		'en-us' => _('English (US)'),
		'en-gb' => _('English (UK)'),
		'da-dk' => _('Danish'),
		'nl-nl' => _('Dutch'),
		// 'fr' => _('French (France)'),
		'fr-ca' => _('French (Canada)'),
		'de-de' => _('German'),
		'it-it' => _('Italian'),
		'ja-jp' => _('Japanese'),
		'pl-pl' => _('Polish'),
		'pt-br' => _('Portuguese (Brazil)'),
		'ru-ru' => _('Russian'),
		'es-es' => _('Spanish (Spain)')
		// 'se' => _('Swedish')
	);
?>