<?php
/*
  $Id$
  part of TeeBX(R) VoIP communication platform. http://www.teebx.com
*/

	$audio_codecs = array(
		'gsm' => 'GSM',
		'ulaw' => 'G.711 u-law',
		'alaw' => 'G.711 A-law',
		'g722' => 'G.722',
		'g723' => 'G.723.1',
		'g726aal2' => 'G.726 (AAL2)',
		'g726' => 'G.726 (RFC3551)',
		'g729' => 'G.729A',
		'ilbc' => 'iLBC',
		'speex' => 'SpeeX',
		'adpcm' => 'ADPCM',
		'slin' => '16 bit Signed Linear PCM',
		'lpc10' => 'LPC10'
	);

	$video_codecs = array(
		'h261' => 'H.261',
		'h263' => 'H.263',
		'h263p' => 'H.263+',
		'h264' => 'H.264'
	);
?>