<?php
/*
  $Id$
part of BoneOS build platform (http://www.teebx.com/)
Copyright(C) 2010 - 2012 Giovanni Vallesi (http://www.teebx.com).
All rights reserved.
*/

	$ddnsProviders = array(
		'dhs' => 'DHS',
		'dyndns' => 'DynDNS',
		'dyndns-custom' => 'DynDNS (custom)',
		'dyndns-static' => 'DynDNS (static)',
		'dyns' => 'DyNS',
		'easydns' => 'easyDNS',
		'ezip' => 'EZ-IP',
		'gnudip' => 'GNUDip',
		'hn' => 'HN.ORG',
		'ods' => 'ODS',
		'tzo' => 'TZO',
		'zoneedit' => 'ZoneEdit'
	);
?>